/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation.$invitationId'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppCreateOrganizationRouteImport } from './routes/_app.create-organization'
import { Route as AppOrgRouteImport } from './routes/_app._org'
import { Route as AppOrgIndexRouteImport } from './routes/_app._org.index'
import { Route as AppOrgSitesRouteImport } from './routes/_app._org.sites'
import { Route as AppOrgMembersRouteImport } from './routes/_app._org.members'
import { Route as AppOrgJobsRouteImport } from './routes/_app._org.jobs'
import { Route as AppOrgActivityRouteImport } from './routes/_app._org.activity'
import { Route as AppOrgOrganizationSettingsRouteImport } from './routes/_app._org.organization.settings'
import { Route as AppOrgOrganizationSecurityRouteImport } from './routes/_app._org.organization.security'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateOrganizationRoute = AppCreateOrganizationRouteImport.update({
  id: '/create-organization',
  path: '/create-organization',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgRoute = AppOrgRouteImport.update({
  id: '/_org',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgIndexRoute = AppOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgSitesRoute = AppOrgSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgMembersRoute = AppOrgMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgJobsRoute = AppOrgJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgActivityRoute = AppOrgActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppOrgRoute,
} as any)
const AppOrgOrganizationSettingsRoute =
  AppOrgOrganizationSettingsRouteImport.update({
    id: '/organization/settings',
    path: '/organization/settings',
    getParentRoute: () => AppOrgRoute,
  } as any)
const AppOrgOrganizationSecurityRoute =
  AppOrgOrganizationSecurityRouteImport.update({
    id: '/organization/security',
    path: '/organization/security',
    getParentRoute: () => AppOrgRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppOrgIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/create-organization': typeof AppCreateOrganizationRoute
  '/settings': typeof AppSettingsRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/activity': typeof AppOrgActivityRoute
  '/jobs': typeof AppOrgJobsRoute
  '/members': typeof AppOrgMembersRoute
  '/sites': typeof AppOrgSitesRoute
  '/organization/security': typeof AppOrgOrganizationSecurityRoute
  '/organization/settings': typeof AppOrgOrganizationSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof AppOrgIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/create-organization': typeof AppCreateOrganizationRoute
  '/settings': typeof AppSettingsRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/activity': typeof AppOrgActivityRoute
  '/jobs': typeof AppOrgJobsRoute
  '/members': typeof AppOrgMembersRoute
  '/sites': typeof AppOrgSitesRoute
  '/organization/security': typeof AppOrgOrganizationSecurityRoute
  '/organization/settings': typeof AppOrgOrganizationSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/_org': typeof AppOrgRouteWithChildren
  '/_app/create-organization': typeof AppCreateOrganizationRoute
  '/_app/settings': typeof AppSettingsRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/_app/_org/activity': typeof AppOrgActivityRoute
  '/_app/_org/jobs': typeof AppOrgJobsRoute
  '/_app/_org/members': typeof AppOrgMembersRoute
  '/_app/_org/sites': typeof AppOrgSitesRoute
  '/_app/_org/': typeof AppOrgIndexRoute
  '/_app/_org/organization/security': typeof AppOrgOrganizationSecurityRoute
  '/_app/_org/organization/settings': typeof AppOrgOrganizationSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/health'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/create-organization'
    | '/settings'
    | '/accept-invitation/$invitationId'
    | '/oauth/consent'
    | '/activity'
    | '/jobs'
    | '/members'
    | '/sites'
    | '/organization/security'
    | '/organization/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/health'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/create-organization'
    | '/settings'
    | '/accept-invitation/$invitationId'
    | '/oauth/consent'
    | '/activity'
    | '/jobs'
    | '/members'
    | '/sites'
    | '/organization/security'
    | '/organization/settings'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/health'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/_app/_org'
    | '/_app/create-organization'
    | '/_app/settings'
    | '/accept-invitation/$invitationId'
    | '/oauth/consent'
    | '/_app/_org/activity'
    | '/_app/_org/jobs'
    | '/_app/_org/members'
    | '/_app/_org/sites'
    | '/_app/_org/'
    | '/_app/_org/organization/security'
    | '/_app/_org/organization/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  OauthConsentRoute: typeof OauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create-organization': {
      id: '/_app/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof AppCreateOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_org': {
      id: '/_app/_org'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppOrgRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_org/': {
      id: '/_app/_org/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppOrgIndexRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/_org/sites': {
      id: '/_app/_org/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AppOrgSitesRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/_org/members': {
      id: '/_app/_org/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppOrgMembersRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/_org/jobs': {
      id: '/_app/_org/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppOrgJobsRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/_org/activity': {
      id: '/_app/_org/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppOrgActivityRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/_org/organization/settings': {
      id: '/_app/_org/organization/settings'
      path: '/organization/settings'
      fullPath: '/organization/settings'
      preLoaderRoute: typeof AppOrgOrganizationSettingsRouteImport
      parentRoute: typeof AppOrgRoute
    }
    '/_app/_org/organization/security': {
      id: '/_app/_org/organization/security'
      path: '/organization/security'
      fullPath: '/organization/security'
      preLoaderRoute: typeof AppOrgOrganizationSecurityRouteImport
      parentRoute: typeof AppOrgRoute
    }
  }
}

interface AppOrgRouteChildren {
  AppOrgActivityRoute: typeof AppOrgActivityRoute
  AppOrgJobsRoute: typeof AppOrgJobsRoute
  AppOrgMembersRoute: typeof AppOrgMembersRoute
  AppOrgSitesRoute: typeof AppOrgSitesRoute
  AppOrgIndexRoute: typeof AppOrgIndexRoute
  AppOrgOrganizationSecurityRoute: typeof AppOrgOrganizationSecurityRoute
  AppOrgOrganizationSettingsRoute: typeof AppOrgOrganizationSettingsRoute
}

const AppOrgRouteChildren: AppOrgRouteChildren = {
  AppOrgActivityRoute: AppOrgActivityRoute,
  AppOrgJobsRoute: AppOrgJobsRoute,
  AppOrgMembersRoute: AppOrgMembersRoute,
  AppOrgSitesRoute: AppOrgSitesRoute,
  AppOrgIndexRoute: AppOrgIndexRoute,
  AppOrgOrganizationSecurityRoute: AppOrgOrganizationSecurityRoute,
  AppOrgOrganizationSettingsRoute: AppOrgOrganizationSettingsRoute,
}

const AppOrgRouteWithChildren =
  AppOrgRoute._addFileChildren(AppOrgRouteChildren)

interface AppRouteChildren {
  AppOrgRoute: typeof AppOrgRouteWithChildren
  AppCreateOrganizationRoute: typeof AppCreateOrganizationRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOrgRoute: AppOrgRouteWithChildren,
  AppCreateOrganizationRoute: AppCreateOrganizationRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  OauthConsentRoute: OauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
