const HOTKEY_SCOPES = [
  "global",
  "home",
  "jobs",
  "jobs-workspace",
  "job-create",
  "job-detail",
  "sites",
  "sites-workspace",
  "members",
  "settings",
  "labels-settings",
  "map",
] as const;

export type HotkeyScope = (typeof HOTKEY_SCOPES)[number];

export const HOTKEY_GROUPS = [
  "Navigation",
  "Layout",
  "Agent",
  "Home",
  "Jobs",
  "Job drawer",
  "Sites",
  "Sites workspace",
  "Members",
  "Settings",
  "Map",
] as const;

type HotkeyGroup = (typeof HOTKEY_GROUPS)[number];

export interface HotkeyDefinition {
  readonly group: HotkeyGroup;
  readonly hotkey: string;
  readonly id: string;
  readonly label: string;
  readonly scope: HotkeyScope;
  readonly when?: string;
}

export const HOTKEYS = {
  help: {
    group: "Layout",
    hotkey: "?",
    id: "help",
    label: "Show keyboard shortcuts",
    scope: "global",
  },
  helpAlternate: {
    group: "Layout",
    hotkey: "Mod+/",
    id: "helpAlternate",
    label: "Show keyboard shortcuts",
    scope: "global",
  },
  toggleSidebar: {
    group: "Layout",
    hotkey: "Mod+B",
    id: "toggleSidebar",
    label: "Toggle sidebar",
    scope: "global",
  },
  openAgentChat: {
    group: "Agent",
    hotkey: "Mod+J",
    id: "openAgentChat",
    label: "Ask Ceird",
    scope: "global",
    when: "Organization is active",
  },
  agentSubmit: {
    group: "Agent",
    hotkey: "Mod+Enter",
    id: "agentSubmit",
    label: "Send agent message",
    scope: "global",
    when: "Agent composer is focused",
  },
  agentStop: {
    group: "Agent",
    hotkey: "Mod+.",
    id: "agentStop",
    label: "Stop agent response",
    scope: "global",
    when: "Agent turn is active",
  },
  goHome: {
    group: "Navigation",
    hotkey: "G H",
    id: "goHome",
    label: "Go to Home",
    scope: "global",
  },
  goJobs: {
    group: "Navigation",
    hotkey: "G J",
    id: "goJobs",
    label: "Go to Jobs",
    scope: "global",
  },
  goJobsWorkspace: {
    group: "Navigation",
    hotkey: "G R",
    id: "goJobsWorkspace",
    label: "Go to Jobs Workspace",
    scope: "global",
    when: "Viewer can access the realtime jobs preview",
  },
  goSites: {
    group: "Navigation",
    hotkey: "G S",
    id: "goSites",
    label: "Go to Sites",
    scope: "global",
  },
  goSitesWorkspace: {
    group: "Navigation",
    hotkey: "G X",
    id: "goSitesWorkspace",
    label: "Go to Sites workspace",
    scope: "global",
    when: "Electric Sites workspace preview is enabled",
  },
  goActivity: {
    group: "Navigation",
    hotkey: "G A",
    id: "goActivity",
    label: "Go to Activity",
    scope: "global",
  },
  goOrganizationSecurity: {
    group: "Navigation",
    hotkey: "G Y",
    id: "goOrganizationSecurity",
    label: "Go to Security activity",
    scope: "global",
    when: "Viewer can administer organization",
  },
  goMembers: {
    group: "Navigation",
    hotkey: "G M",
    id: "goMembers",
    label: "Go to Members",
    scope: "global",
  },
  goSettings: {
    group: "Navigation",
    hotkey: "G T",
    id: "goSettings",
    label: "Go to user settings",
    scope: "global",
  },
  goOrganizationSettings: {
    group: "Navigation",
    hotkey: "G W",
    id: "goOrganizationSettings",
    label: "Go to organization settings",
    scope: "global",
    when: "Viewer can administer organization",
  },
  goOrganizationLabels: {
    group: "Navigation",
    hotkey: "G L",
    id: "goOrganizationLabels",
    label: "Go to Labels settings",
    scope: "global",
    when: "Viewer can administer organization",
  },
  goMap: {
    group: "Navigation",
    hotkey: "G P",
    id: "goMap",
    label: "Go to Map",
    scope: "global",
  },
  openOrganizationSwitcher: {
    group: "Navigation",
    hotkey: "G O",
    id: "openOrganizationSwitcher",
    label: "Switch organization",
    scope: "global",
    when: "Multiple organizations are available",
  },
  homeCreateJob: {
    group: "Home",
    hotkey: "N",
    id: "homeCreateJob",
    label: "Create job",
    scope: "home",
    when: "Organization home is active",
  },
  switchOrganization1: {
    group: "Navigation",
    hotkey: "Mod+1",
    id: "switchOrganization1",
    label: "Switch to team 1",
    scope: "global",
    when: "Organization switcher is open",
  },
  switchOrganization2: {
    group: "Navigation",
    hotkey: "Mod+2",
    id: "switchOrganization2",
    label: "Switch to team 2",
    scope: "global",
    when: "Organization switcher is open",
  },
  switchOrganization3: {
    group: "Navigation",
    hotkey: "Mod+3",
    id: "switchOrganization3",
    label: "Switch to team 3",
    scope: "global",
    when: "Organization switcher is open",
  },
  switchOrganization4: {
    group: "Navigation",
    hotkey: "Mod+4",
    id: "switchOrganization4",
    label: "Switch to team 4",
    scope: "global",
    when: "Organization switcher is open",
  },
  switchOrganization5: {
    group: "Navigation",
    hotkey: "Mod+5",
    id: "switchOrganization5",
    label: "Switch to team 5",
    scope: "global",
    when: "Organization switcher is open",
  },
  switchOrganization6: {
    group: "Navigation",
    hotkey: "Mod+6",
    id: "switchOrganization6",
    label: "Switch to team 6",
    scope: "global",
    when: "Organization switcher is open",
  },
  switchOrganization7: {
    group: "Navigation",
    hotkey: "Mod+7",
    id: "switchOrganization7",
    label: "Switch to team 7",
    scope: "global",
    when: "Organization switcher is open",
  },
  switchOrganization8: {
    group: "Navigation",
    hotkey: "Mod+8",
    id: "switchOrganization8",
    label: "Switch to team 8",
    scope: "global",
    when: "Organization switcher is open",
  },
  switchOrganization9: {
    group: "Navigation",
    hotkey: "Mod+9",
    id: "switchOrganization9",
    label: "Switch to team 9",
    scope: "global",
    when: "Organization switcher is open",
  },
  jobsSearch: {
    group: "Jobs",
    hotkey: "/",
    id: "jobsSearch",
    label: "Search jobs",
    scope: "jobs",
  },
  jobsCreate: {
    group: "Jobs",
    hotkey: "N",
    id: "jobsCreate",
    label: "Create job",
    scope: "jobs",
    when: "Viewer can create jobs",
  },
  jobsRefresh: {
    group: "Jobs",
    hotkey: "R",
    id: "jobsRefresh",
    label: "Refresh jobs",
    scope: "jobs",
  },
  jobsListView: {
    group: "Jobs",
    hotkey: "V L",
    id: "jobsListView",
    label: "List view",
    scope: "jobs",
  },
  jobsMapView: {
    group: "Jobs",
    hotkey: "V M",
    id: "jobsMapView",
    label: "Map view",
    scope: "jobs",
  },
  jobsNearMe: {
    group: "Jobs",
    hotkey: "V N",
    id: "jobsNearMe",
    label: "Rank jobs near me",
    scope: "jobs",
    when: "Internal job filters are available",
  },
  jobsSavedViews: {
    group: "Jobs",
    hotkey: "V S",
    id: "jobsSavedViews",
    label: "Saved views",
    scope: "jobs",
  },
  jobsClearFilters: {
    group: "Jobs",
    hotkey: "C",
    id: "jobsClearFilters",
    label: "Clear filters",
    scope: "jobs",
    when: "Filters are active",
  },
  jobsDismissNotice: {
    group: "Jobs",
    hotkey: "Escape",
    id: "jobsDismissNotice",
    label: "Dismiss notice",
    scope: "jobs",
    when: "Notice is visible",
  },
  jobsWorkspaceSearch: {
    group: "Jobs",
    hotkey: "/",
    id: "jobsWorkspaceSearch",
    label: "Search jobs workspace",
    scope: "jobs-workspace",
  },
  jobsWorkspaceListView: {
    group: "Jobs",
    hotkey: "V L",
    id: "jobsWorkspaceListView",
    label: "Jobs workspace list view",
    scope: "jobs-workspace",
  },
  jobsWorkspaceBoardView: {
    group: "Jobs",
    hotkey: "V B",
    id: "jobsWorkspaceBoardView",
    label: "Jobs workspace board view",
    scope: "jobs-workspace",
  },
  jobsWorkspaceNextRow: {
    group: "Jobs",
    hotkey: "J",
    id: "jobsWorkspaceNextRow",
    label: "Select next job row",
    scope: "jobs-workspace",
    when: "Jobs workspace rows are visible",
  },
  jobsWorkspacePreviousRow: {
    group: "Jobs",
    hotkey: "K",
    id: "jobsWorkspacePreviousRow",
    label: "Select previous job row",
    scope: "jobs-workspace",
    when: "Jobs workspace rows are visible",
  },
  jobsWorkspaceRowActions: {
    group: "Jobs",
    hotkey: "Enter",
    id: "jobsWorkspaceRowActions",
    label: "Focus selected job row actions",
    scope: "jobs-workspace",
    when: "A jobs workspace row is selected",
  },
  jobsWorkspaceCycleSort: {
    group: "Jobs",
    hotkey: "S",
    id: "jobsWorkspaceCycleSort",
    label: "Cycle jobs workspace sort",
    scope: "jobs-workspace",
  },
  jobsWorkspaceClearFilters: {
    group: "Jobs",
    hotkey: "C",
    id: "jobsWorkspaceClearFilters",
    label: "Clear jobs workspace filters",
    scope: "jobs-workspace",
    when: "Filters are active",
  },
  jobCreateSubmit: {
    group: "Job drawer",
    hotkey: "Mod+Enter",
    id: "jobCreateSubmit",
    label: "Submit create form",
    scope: "job-create",
  },
  jobCreateCancel: {
    group: "Job drawer",
    hotkey: "Escape",
    id: "jobCreateCancel",
    label: "Cancel create form",
    scope: "job-create",
    when: "Not creating",
  },
  jobCreatePriority: {
    group: "Job drawer",
    hotkey: "P",
    id: "jobCreatePriority",
    label: "Open priority select",
    scope: "job-create",
  },
  jobCreateSite: {
    group: "Job drawer",
    hotkey: "S",
    id: "jobCreateSite",
    label: "Open site select",
    scope: "job-create",
  },
  jobCreateContact: {
    group: "Job drawer",
    hotkey: "C",
    id: "jobCreateContact",
    label: "Open contact select",
    scope: "job-create",
  },
  jobDetailClose: {
    group: "Job drawer",
    hotkey: "Escape",
    id: "jobDetailClose",
    label: "Close drawer",
    scope: "job-detail",
  },
  jobDetailStatus: {
    group: "Job drawer",
    hotkey: "S",
    id: "jobDetailStatus",
    label: "Focus next-status select",
    scope: "job-detail",
  },
  jobDetailComment: {
    group: "Job drawer",
    hotkey: "C",
    id: "jobDetailComment",
    label: "Focus comment",
    scope: "job-detail",
  },
  jobDetailVisit: {
    group: "Job drawer",
    hotkey: "V",
    id: "jobDetailVisit",
    label: "Focus visit note or date",
    scope: "job-detail",
  },
  jobDetailCollaborators: {
    group: "Job drawer",
    hotkey: "E",
    id: "jobDetailCollaborators",
    label: "Focus collaborators",
    scope: "job-detail",
  },
  jobDetailSite: {
    group: "Job drawer",
    hotkey: "L",
    id: "jobDetailSite",
    label: "Focus site assignment",
    scope: "job-detail",
  },
  jobDetailSubmit: {
    group: "Job drawer",
    hotkey: "Mod+Enter",
    id: "jobDetailSubmit",
    label: "Submit focused form area",
    scope: "job-detail",
  },
  sitesCreate: {
    group: "Sites",
    hotkey: "N",
    id: "sitesCreate",
    label: "Create site",
    scope: "sites",
    when: "Viewer can create sites",
  },
  sitesListView: {
    group: "Sites",
    hotkey: "V L",
    id: "sitesListView",
    label: "List view",
    scope: "sites",
  },
  sitesMapView: {
    group: "Sites",
    hotkey: "V M",
    id: "sitesMapView",
    label: "Map view",
    scope: "sites",
  },
  sitesNearMe: {
    group: "Sites",
    hotkey: "V N",
    id: "sitesNearMe",
    label: "Rank sites near me",
    scope: "sites",
  },
  sitesWorkspaceSearch: {
    group: "Sites workspace",
    hotkey: "/",
    id: "sitesWorkspaceSearch",
    label: "Search sites workspace",
    scope: "sites-workspace",
  },
  sitesWorkspaceNextRow: {
    group: "Sites workspace",
    hotkey: "ArrowDown",
    id: "sitesWorkspaceNextRow",
    label: "Select next site",
    scope: "sites-workspace",
    when: "Sites workspace list has rows",
  },
  sitesWorkspacePreviousRow: {
    group: "Sites workspace",
    hotkey: "ArrowUp",
    id: "sitesWorkspacePreviousRow",
    label: "Select previous site",
    scope: "sites-workspace",
    when: "Sites workspace list has rows",
  },
  membersInvite: {
    group: "Members",
    hotkey: "N",
    id: "membersInvite",
    label: "Invite teammate",
    scope: "members",
  },
  membersSubmit: {
    group: "Members",
    hotkey: "Mod+Enter",
    id: "membersSubmit",
    label: "Submit invite form",
    scope: "members",
    when: "Invite dialog is open",
  },
  membersRole: {
    group: "Members",
    hotkey: "R",
    id: "membersRole",
    label: "Focus invite role select",
    scope: "members",
    when: "Invite dialog is open",
  },
  settingsSubmit: {
    group: "Settings",
    hotkey: "Mod+Enter",
    id: "settingsSubmit",
    label: "Submit focused form",
    scope: "settings",
  },
  labelsSettingsSearch: {
    group: "Settings",
    hotkey: "/",
    id: "labelsSettingsSearch",
    label: "Search labels",
    scope: "labels-settings",
  },
  mapZoomIn: {
    group: "Map",
    hotkey: "Shift+=",
    id: "mapZoomIn",
    label: "Zoom in",
    scope: "map",
    when: "Zoom controls are visible",
  },
  mapZoomOut: {
    group: "Map",
    hotkey: "-",
    id: "mapZoomOut",
    label: "Zoom out",
    scope: "map",
    when: "Zoom controls are visible",
  },
  mapResetBearing: {
    group: "Map",
    hotkey: "0",
    id: "mapResetBearing",
    label: "Reset bearing",
    scope: "map",
    when: "Compass control is visible",
  },
  mapLocate: {
    group: "Map",
    hotkey: "L",
    id: "mapLocate",
    label: "Locate",
    scope: "map",
    when: "Locate control is visible",
  },
  mapFullscreen: {
    group: "Map",
    hotkey: "F",
    id: "mapFullscreen",
    label: "Fullscreen",
    scope: "map",
    when: "Fullscreen control is visible",
  },
} as const satisfies Record<string, HotkeyDefinition>;

export type HotkeyId = keyof typeof HOTKEYS;
